Explicitly use '127.0.0.1' instead of 'localhost' as dev proxy target
Otherwise the OS can choose ipv6 which results in mixing protocols

```
http proxy error:
Error: connect ECONNREFUSED ::1:8080
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)
```