Fix the `TransientObjectException` error in the syncer (#343)
* Fix syncer

Under certain circumstances, where a large number of modifying processes take place in a transaction, e.g. 10 groups are deleted, 10 groups are created, these new groups are directly assigned to many new users, it can happen that the syncer aborts with the following exception:

java.lang.IllegalStateException: org.hibernate.TransientObjectException: persistent instance references an unsaved transient instance of ‘org.cryptomator.hub.entities.Authority’ (save the transient instance before flushing)

Since the tansaction is canceled here, the same error occurs again during the next sync process.

The reason for this is that we mix managed (which already exist in the DB) and unmanaged (which we map from Keycloak directly into entities) Hibernate entities and from a certain complexity, the Hibernate session management no longer gets this cleanly assigned, especially if an object with the same ID exists as both managed and unmanaged.

* Fix potential nullpointer if a new user was added to a group